---
- name: Install SIMAM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - command: "docker ps -a"
      register: dir_out
    - debug: var={{item}}
      with_items: dir_out.stdout_lines
